### ISSUE TITLE
Add formatter for LocalDateTime or Locale

### ISSUE THREAD

**Issue by chexxor** [slamdata/purescript-formatters#21]
Looks like there's no formatter for a DateTime in a [Locale](https://github.com/purescript/purescript-datetime/blob/v3.0.0/src/Data/DateTime/Locale.purs#L15-L15)/[LocalValue](https://github.com/purescript/purescript-datetime/blob/v3.0.0/src/Data/DateTime/Locale.purs#L40)/[LocalDateTime](https://github.com/purescript/purescript-datetime/blob/v3.0.0/src/Data/DateTime/Locale.purs#L65).

I don't have an immediate need for this formatter, but it's worth noting that this ability is missing.

Actually creating an instance of that LocalDateTime is a different challenge, as it depends on a mapping from locale (America/Chicago) to the timezone/offset (CST/-500) that will be observed for that specific DateTime. I spent lots of time thinking of the problem, so it's worth noting this complexity here, as I didn't find it noted in any other PS library.

**Comment by garyb** [comment]
Closing this as Locale stuff is gone now.
