### ISSUE TITLE
unformatNumber for very large numbers returns negative number

### ISSUE THREAD

**Issue by Houndolon** [slamdata/purescript-formatters#38]
I'm not sure if this is related to #16, but

    > unformatNumber "0.0" "1507142848002.0"
    (Right -390672894.0)

For reference, the number I'm trying to parse was created by `now <#> unInstant <#> unwrap <#> show`.

**Comment by safareli** [comment]
it's related

**Comment by safareli** [comment]
Will close this as duplicate, thanks for reporting tho!
